openapi: 3.0.3
servers:
- url: http://localhost:2081/
  description: url Local
- url: https://dev.nttdata.com/mspayment/
  description: url Desarrollo
- url: https://nttdata.com/mspayment/
  description: url Produccion